language: node_js
install:
- curl -s https://www.parse.com/downloads/cloud_code/installer.sh | sudo /bin/bash
before_script:
- /bin/echo "${ACCOUNT_KEY}" | /usr/local/bin/parse configure accountkey -d
script:
- /usr/local/bin/parse deploy -f
env:
  global:
    secure: pO28Vik6+r9Za84pcdkeJT9lW3MVms+MroO0UpWjNx8URjLYnEFOlSGe8ngxrJJCcf14XXoSPfotuMr2BH5kGDxeyvInXo9YUA+xAmqqrddv+inbUqNHmGJcppfrl1o8MRTHwOqO++zSmDoAUCILTddSzfAaOAB68XrNEqq9sjcunGqH9G/S4N7EBRg8vdbwMDwPlEi0arP6v+T4U7c+0YteWGdDDrXqeB/OX52qCuqnesct9RHuRP76KtOItsn+lo6W7Urebnz8n1SvcOF6k4tYgZ031GD6PfOA2yQRT3TK6hLbitrLTsWdryipaF4l6uX0Dl34LmROcAcOkAXmuEXJv3zdlhfgIkD3q+UMEQud56TUXiAiLQttuz33Dh4SU5OanjStiCflhj6gmkiqXQ6hGQYS6msLT6TUH6TnYOOKnDJhU0IRNOmWK+G77KvftBvclIXtbBvQSZojRksCZn12GrPCOwwtl8goXl9IOjCitm0ijALKKjWHMb81nDZxitu7J6h9qI3WVIzbvVxirSdjZ/7SFvkcigk9jZDSAUVS1Qi46QXLvif7IrEHJAKxzqhKkIryqXJGeNlP3Iob5VSyGIjFlcRjRGp8bdcND3+U7dv/f3nc+xuCQXSQpjL9fRrgGI+ImlOOEeWofaEiu9mpzeoVVz4IEdr77IfLvfM=
